services:
  analysis:
    build: ./analysis
    environment:
      - PARSED_DATA_FILE=${PARSED_DATA_FILE}
      - OPTIONS_RECAP_FILE=${OPTIONS_RECAP_FILE}
      - HISTORICAL_DATA_DIR=${HISTORICAL_DATA_DIR}
  scrape:
    build: ./scrape
    environment:
      - INCOMING_ALERTS_DIRECTORY=${INCOMING_ALERTS_DIRECTORY}