services:
  analysis:
    build: ./analysis
    environment:
      - PARSED_DATA_FILE=${PARSED_DATA_FILE}
      - OPTIONS_RECAP_FILE=${OPTIONS_RECAP_FILE}
      - HISTORICAL_DATA_DIR=${HISTORICAL_DATA_DIR}
  historical:
    build: ./alerts/historical
    environment:
      - HISTORICAL_ALERTS_HOSTNAME=${HISTORICAL_ALERTS_HOSTNAME}
      - HISTORICAL_ALERTS_PORT=${HISTORICAL_ALERTS_PORT}
  realtime:
    build: ./alerts/realtime
    environment:
      - REALTIME_ALERTS_HOSTNAME=${REALTIME_ALERTS_HOSTNAME}
      - REALTIME_ALERTS_PORT=${REALTIME_ALERTS_PORT}