services:
  proxy:
    build:
      context: ./src/node/proxy
      dockerfile: Dockerfile
    environment:
      - PROXY_PORT=${PROXY_PORT}
      - HISTORICAL_SERVER_HOSTNAME=${HISTORICAL_SERVER_HOSTNAME}
      - HISTORICAL_SERVER_PORT=${HISTORICAL_SERVER_PORT}
      - REALTIME_SERVER_HOSTNAME=${REALTIME_SERVER_HOSTNAME}
      - REALTIME_SERVER_PORT=${REALTIME_SERVER_PORT}
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
  db-store:
    build:
      context: ./src/node/database
      dockerfile: Dockerfile
    depends_on:
      - "mongodb"
    environment:
      - DB_STORE_PORT=${DB_STORE_PORT}
      - DATABASE_URI=${DATABASE_URI}
  historical:
    build:
      context: ./src/python/historical
      dockerfile: Dockerfile
    environment:
      - HISTORICAL_SERVER_HOSTNAME=${HISTORICAL_SERVER_HOSTNAME}
      - HISTORICAL_SERVER_PORT=${HISTORICAL_SERVER_PORT}
      - DB_STORE_HOSTNAME=${DB_STORE_HOSTNAME}
      - DB_STORE_PORT=${DB_STORE_PORT}
  realtime:
    build:
      context: ./src/python/realtime
      dockerfile: Dockerfile
    environment:
      - REALTIME_SERVER_HOSTNAME=${REALTIME_SERVER_HOSTNAME}
      - REALTIME_SERVER_PORT=${REALTIME_SERVER_PORT}
      - DB_STORE_HOSTNAME=${DB_STORE_HOSTNAME}
      - DB_STORE_PORT=${DB_STORE_PORT}
  mongodb:
    image: mongo:latest
    volumes:
      - ./data/database:/data/db
