services:
  proxy:
    build: ./src/node/proxy
    environment:
      - PROXY_PORT=${PROXY_PORT}
      - HISTORICAL_SERVER_HOSTNAME=${HISTORICAL_SERVER_HOSTNAME}
      - HISTORICAL_SERVER_PORT=${HISTORICAL_SERVER_PORT}
      - REALTIME_SERVER_HOSTNAME=${REALTIME_SERVER_HOSTNAME}
      - REALTIME_SERVER_PORT=${REALTIME_SERVER_PORT}
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
  db-store:
    build: ./src/node/database
    depends_on:
      - "mongodb"
    environment:
      - DB_STORE_PORT=${DB_STORE_PORT}
      - DATABASE_URI=${DATABASE_URI}
  # analysis:
  #   build: ./src/python/analysis
  #   environment:
  #     - PARSED_DATA_FILE=${PARSED_DATA_FILE}
  #     - OPTIONS_RECAP_FILE=${OPTIONS_RECAP_FILE}
  #     - HISTORICAL_DATA_DIR=${HISTORICAL_DATA_DIR}
  historical:
    build: ./src/python/historical
    environment:
      - HISTORICAL_SERVER_HOSTNAME=${HISTORICAL_SERVER_HOSTNAME}
      - HISTORICAL_SERVER_PORT=${HISTORICAL_SERVER_PORT}
      - DB_STORE_HOSTNAME=${DB_STORE_HOSTNAME}
      - DB_STORE_PORT=${DB_STORE_PORT}
  realtime:
    build: ./src/python/realtime
    environment:
      - REALTIME_SERVER_HOSTNAME=${REALTIME_SERVER_HOSTNAME}
      - REALTIME_SERVER_PORT=${REALTIME_SERVER_PORT}
      - DB_STORE_HOSTNAME=${DB_STORE_HOSTNAME}
      - DB_STORE_PORT=${DB_STORE_PORT}
  mongodb:
    image: mongo:latest
    volumes:
      - ./data/database:/data/db