services:
  # analysis:
  #   build: ./analysis
  #   environment:
  #     - PARSED_DATA_FILE=${PARSED_DATA_FILE}
  #     - OPTIONS_RECAP_FILE=${OPTIONS_RECAP_FILE}
  #     - HISTORICAL_DATA_DIR=${HISTORICAL_DATA_DIR}
  historical:
    build: ./alerts/historical
    environment:
      - HISTORICAL_SERVER_HOSTNAME=${HISTORICAL_SERVER_HOSTNAME}
      - HISTORICAL_SERVER_PORT=${HISTORICAL_SERVER_PORT}
  realtime:
    build: ./alerts/realtime
    environment:
      - REALTIME_SERVER_HOSTNAME=${REALTIME_SERVER_HOSTNAME}
      - REALTIME_SERVER_PORT=${REALTIME_SERVER_PORT}